# Generated by Django 3.0.7 on 2020-06-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0002_montesuacompra_rede'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonteSuaCompra',
            new_name='SuaCompra',
        ),
        migrations.AlterField(
            model_name='rede',
            name='cor',
            field=models.CharField(choices=[('VERMELHA', 'Vermelha'), ('AMARELA', 'Amarela'), ('VERDE', 'Verde'), ('AZUL', 'Azul')], max_length=10, verbose_name='Cor'),
        ),
    ]
