# Generated by Django 3.0.7 on 2020-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0003_auto_20200628_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='preco',
            field=models.CharField(choices=[('R$ 60.00', '60.00')], default=1, max_length=10, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
