# Generated by Django 3.0.7 on 2020-06-28 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojaApp', '0004_rede_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanosDePrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(choices=[('R$ 10.00', '10.00')], max_length=10, verbose_name='Panos')),
            ],
        ),
        migrations.AddField(
            model_name='suacompra',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
