# Generated by Django 3.0.7 on 2020-06-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0006_remove_suacompra_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panosdeprato',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='rede',
            name='preco',
        ),
        migrations.AddField(
            model_name='panosdeprato',
            name='valor',
            field=models.CharField(choices=[('R$ 10.00', '10.00')], default=1, max_length=10, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rede',
            name='valor',
            field=models.CharField(choices=[('R$ 60.00', '60.00')], default=1, max_length=10, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
