# Generated by Django 3.0.7 on 2020-06-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0007_auto_20200628_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='suacompra',
            name='panos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lojaApp.PanosDePrato', verbose_name='Panos'),
            preserve_default=False,
        ),
    ]
