# Generated by Django 3.0.7 on 2020-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0008_suacompra_panos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('VERMELHA', 'Vermelha'), ('AMARELA', 'Amarela'), ('VERDE', 'Verde'), ('AZUL', 'Azul')], max_length=10, verbose_name='Cor')),
                ('valor', models.CharField(choices=[('R$ 60.00', '60.00')], max_length=10, verbose_name='Valor')),
            ],
        ),
    ]
