# Generated by Django 3.0.7 on 2020-06-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0009_mantas'),
    ]

    operations = [
        migrations.AddField(
            model_name='suacompra',
            name='mantas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lojaApp.Mantas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suacompra',
            name='panos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaApp.PanosDePrato'),
        ),
        migrations.AlterField(
            model_name='suacompra',
            name='rede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaApp.Rede'),
        ),
    ]
