# Generated by Django 3.0.7 on 2020-06-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaApp', '0010_auto_20200628_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantas',
            name='valor',
            field=models.CharField(choices=[('R$ 30.00', '30.00')], max_length=10, verbose_name='Valor'),
        ),
    ]
